server:
  port: 8000

spring:
  application:
    name: m-blog

  rabbitmq:
    host: 47.120.15.196
    port: 5672
    username: admin
    password: 123
    virtual-host: /  //虚拟机
    listener:
      direct:
        prefetch: 1 #每次获取一条消息（消费预取限制）

  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #   Druid数据源配置
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      #配置从连接池获取连接时，是否检查连接有效性，true每次都检查；false不检查。做了这个配置会降低性能。
      testOnBorrow: false
      #配置向连接池归还连接时，是否检查连接有效性，true每次都检查；false不检查。做了这个配置会降低性能。
      testOnReturn: false
      #打开PsCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      #合并多个DruidDatasource的监控数据
      useGlobalDataSourceStat: true
      #通过connectProperties属性来打开mergesql功能罗慢sQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;

  redis:
    host: 47.120.15.196
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password:
    port: 6379
    timeout: 5000

  main:
    allow-bean-definition-overriding: true     #当出现相同名字的类进行注册时，准许覆盖注册
#  config:
#    activate:
#      on-profile: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true                # 开启驼峰命名法
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-field: deleted
      logic-delete-value: 1
      id-type: auto
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  check-config-location: true                         # 检查xml文件是否存在
  type-aliases-package: com.dragon.pojo.*    # 实体类存放位置



#threadpool:
#  core-pool-size: 10
#  max-pool-size: 20
#  queue-capacity: 1000
#  keep-alive-seconds: 600